### ISSUE TITLE
途中にスペースが入った場合の処理が上手くいってない

### ISSUE THREAD

**Issue by ashcolor** [ashcolor/chord-dictionary#10]
「D7(#9, b13)」のように途中にスペースが入った場合の処理が上手くいってないようです
ja.chordwiki.org/wiki.cgi?c=log…https://twitter.com/surrogatepair/status/1240635686400577538

**Comment by ashcolor** [comment]
文字を選択した場合は優先して選択した文字列を解析にかける。
ホバーでうまく取得できない場合は文字を選択してもらうようにする。

**Comment by graphemecluster** [comment]
直ったのでcloseしましょう。
