### ISSUE TITLE
音符が全部表示されていない

### ISSUE THREAD

**Issue by graphemecluster** [ashcolor/chord-dictionary#12]
### こんな感じ
![こんな感じ](https://user-images.githubusercontent.com/53967830/77687308-25252880-6fd9-11ea-9dec-4c7368e3fe01.png)

**Comment by ashcolor** [comment]
widthは先に取得できるのにheightはできない😢
https://github.com/0xfe/vexflow/wiki/The-VexFlow-FAQ#how-can-i-pre-calculate-the-width-of-a-voice

やるとしたらChordNote.jsの戻り値見て高過ぎたら動的に高さを変更する？

**Comment by graphemecluster** [comment]
Vexflow height と検索したらすぐに出るけど役に立たないのかな？
https://github.com/0xfe/vexflow/issues/629

**Comment by ashcolor** [comment]
`voice.setStave(stave).getBoundingBox().h`で描画する音符する高さが取れました。

これだとちょっと意味合いが違うのでうまくいかず。。。

**Comment by ashcolor** [comment]
いや、yを取ればいけそう
