### ISSUE TITLE
音楽記号のフォントが必要

### ISSUE THREAD

**Issue by graphemecluster** [ashcolor/chord-dictionary#13]
一般のパソコンのフォントはダブルシャープとダブルフラットを入ってなさそうです
![こんな感じ](https://user-images.githubusercontent.com/53967830/77687621-a977ab80-6fd9-11ea-8bc4-4f936ab2dfc4.png)

**Comment by ashcolor** [comment]
@graphemecluster 
こちらの環境だと表示されていて検証できず。。。
css に以下を記載したら直ったりしますか？

```
  font-family: "Arial", YuGothic, "Yu Gothic", "Hiragino Kaku Gothic ProN",
    "ヒラギノ角ゴ ProN W3", "メイリオ", Meiryo, "ＭＳ ゴシック", sans-serif;
```

**Comment by graphemecluster** [comment]
遅くてすみません、直してないようです

**Comment by graphemecluster** [comment]
Fixed #22.
