### ISSUE TITLE
コードから離れても表示されてしまう

### ISSUE THREAD

**Issue by graphemecluster** [ashcolor/chord-dictionary#14]
こんな感じ。cursorは自分が付いた、大体この辺で↓
![こんな感じ](https://user-images.githubusercontent.com/53967830/77688625-5dc60180-6fdb-11ea-949a-d22b21a3582b.png)

ChordWikiでは上が`<br>`の場合、その範囲内でcursor移動すると常時表示されるそうです

**Comment by ashcolor** [comment]
個人的には不便は感じないので保留
