### ISSUE TITLE
偶に楽譜の表示が消えてしまう

### ISSUE THREAD

**Issue by graphemecluster** [ashcolor/chord-dictionary#16]
こんな感じ。消える条件は私にはわからない。
![こんな感じ](https://user-images.githubusercontent.com/53967830/77690658-9e734a00-6fde-11ea-8716-6a7d733113ec.png)

**Comment by graphemecluster** [comment]
多分の[ここらへん](https://github.com/ashcolor/chord-dictionary/blob/master/src/components/Score.vue#L14)の問題かと（無駄）

**Comment by ashcolor** [comment]
developmentブランチで修正済み
