### ISSUE TITLE
拡張機能がオンの状態で他のタブを操作するとアイコンの「ON」の表示が消える

### ISSUE THREAD

**Issue by ashcolor** [ashcolor/chord-dictionary#6]
**再現方法**

1. アイコンをクリックする
2. 別タブで何かしらの操作（未特定）をする
3. 元のタブをみる

拡張機能をは正常に動いているがアイオンの「ON」の文字が消えている。
この状態でアイコンを複数回クリックしても、拡張機能を再度オンにすることができない。
（タブの更新で直る）

**原因**
backgroud.jsでのタブごとの拡張機能のオン、オフの管理がうまくいっていない

**Comment by graphemecluster** [comment]
Fixed https://github.com/ashcolor/chord-dictionary/pull/20.
