### ISSUE TITLE
ホバーモード時に設定画面の文字列がコードとして反応してしまう

### ISSUE THREAD

**Issue by takutoaoi** [ashcolor/chord-dictionary#7]
ホバーをオンにして、設定画面のショートカットの説明にある「Ctrl+Space」などの文字列にカーソルを乗せると、Cやaといった文字列に反応してします。

**Comment by graphemecluster** [comment]
Note: re-fixed https://github.com/ashcolor/chord-dictionary/pull/20#issuecomment-612273512
